trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
#    mac:
#      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    displayName: Windows install rust
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - script: rustup install nightly-2019-04-01
    displayName: Install nightly-2019-04-01
  - script: cargo +nightly-2019-04-01 build --release --all
    displayName: Cargo build
    env: { RUSTFLAGS: "--cfg procmacro2_semver_exempt" }
  - script: cargo +nightly-2019-04-01 test --release --all -- --nocapture
    displayName: Cargo test
    env: {
      RUSTFLAGS: "--cfg procmacro2_semver_exempt",
      RUST_BACKTRACE: 1
    }
