[package]
name = "proc_macro_expander"
version = "0.1.0"
authors = ["roma"]

[dependencies]
dylib = "0.0.3"
quote = "0.6.11"
goblin = "0.0.21"
clap = "2.32.0"

[dependencies.syn]
version = "0.15.26"
features = ["full", "parsing"]

[dependencies.proc-macro2]
version = "0.4.27" #"0.4.24"
features = ["nightly"]
