[package]
name = "proc_macro_server"
version = "0.1.0"
authors = ["roma"]

[dependencies]
dylib = "0.0.3"
serde_derive = "1.0.0"
getset = "0.0.6"
quote = "0.6.5"
rustc-ap-syntax_pos = "235.0.0"
rustc-ap-syntax = "235.0.0"
proc-macro2 = "0.4.13"
goblin = "0.0.17"

[dependencies.syn]
version = "0.14.7"
features = ["full", "parsing"]